### ISSUE TITLE
关于哈利波特项目的一点建议

### ISSUE THREAD

**Issue by paulxin001** [LC1332/CamelBell-Chinese-LoRA#1]
对哈利波特这个项目很感兴趣，但遗憾的是我对哈利波特并不是很了解。为什么不训练中国的四大名著之类的，例如三国演义，这样应该有更多了解故事背景的人可以参与进来。

**Comment by LC1332** [comment]
主要是，chatGPT对三国演义不熟，同样的问题问openai的接口会有很糟糕的结果， 但是这个有一些办法解决 回头看我们更新吧～
